# Generated by Django 5.0.6 on 2024-06-09 15:02

import cuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turboapp_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='turboappuser',
            managers=[
                ('objects', cuser.models.CUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='turboappuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='turboappuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='turboappuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
