# Generated by Django 5.0.6 on 2024-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='New Category', max_length=200),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Subcategory', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('categories', models.ManyToManyField(to='expense_tracker.category')),
            ],
        ),
    ]
