# Generated by Django 5.0.6 on 2024-06-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_category_description_category_title_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
