# Generated by Django 5.0.6 on 2024-06-18 20:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Shop', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='categories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='New Expense', max_length=200),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expense')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(through='expense_tracker.ExpenseCategory', to='expense_tracker.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.shop'),
        ),
    ]
