# Generated by Django 5.0.6 on 2024-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(default='General', through='expense_tracker.ExpenseCategory', to='expense_tracker.category'),
        ),
    ]
