# Generated by Django 5.0.6 on 2024-06-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_alter_expense_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
